services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: engine-auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
