services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: engine-auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    ports:
      - '6650:6650'
    command: >
      /bin/bash -c "bin/pulsar standalone"

volumes:
  postgres_data:
